import { PHOTO } from './assets/photo-data.js';
const photo=document.querySelector('#photo'),hits=document.querySelector('#hits'),detail=document.querySelector('#detail'),face=document.querySelector('#face'),title=document.querySelector('#title'),author=document.querySelector('#author'),grid=document.querySelector('#grid');photo.src=PHOTO;
const books=[{id:'antigona',title:'Antígona · Electra',author:'Sófocles',x:5.6,y:15,w:10.8,h:78.5},{id:'yellow',title:'Edición amarilla',author:'',x:14.5,y:15,w:8.4,h:78.5},{id:'poeta',title:'Romancero gitano · Poeta en Nueva York',author:'Federico García Lorca',x:20.2,y:15.2,w:20.2,h:78},{id:'vida',title:'La vida es sueño',author:'Pedro Calderón de la Barca',x:35.7,y:24.8,w:9,h:66},{id:'capricornio',title:'Capricornio',author:'Helene Knauer Saltarini',x:40.5,y:24,w:11.5,h:66.8},{id:'hamlet',title:'Hamlet',author:'William Shakespeare',x:47.2,y:18,w:29.8,h:69}];
let float=null,pressed=null,holdTimer=null,held=false;
function imageRect(){const iw=photo.naturalWidth||1080,ih=photo.naturalHeight||1920,vr=innerWidth/innerHeight,ir=iw/ih;let w,h,x,y;if(vr>ir){h=innerHeight;w=h*ir;x=(innerWidth-w)/2;y=0}else{w=innerWidth;h=w/ir;x=0;y=(innerHeight-h)/2}return{x,y,w,h}}
function rect(b){const r=imageRect();return{x:r.x+r.w*b.x/100,y:r.y+r.h*b.y/100,w:r.w*b.w/100,h:r.h*b.h/100,img:r}}
function cropStyle(el,b,r=rect(b)){el.style.left=r.x+'px';el.style.top=r.y+'px';el.style.width=r.w+'px';el.style.height=r.h+'px';el.style.backgroundImage=`url(${PHOTO})`;el.style.backgroundSize=`${r.img.w}px ${r.img.h}px`;el.style.backgroundPosition=`${-(r.x-r.img.x)}px ${-(r.y-r.img.y)}px`}
function clearFloat(){if(float){float.remove();float=null}}
function peek(b){clearFloat();float=document.createElement('div');float.className='float';cropStyle(float,b);document.body.appendChild(float);requestAnimationFrame(()=>float?.classList.add('peek'))}
function layout(){hits.innerHTML='';books.forEach(b=>{const r=rect(b),bt=document.createElement('button');bt.className='hit';Object.assign(bt.style,{left:r.x+'px',top:r.y+'px',width:r.w+'px',height:r.h+'px'});bt.onmouseenter=()=>peek(b);bt.onmouseleave=()=>{if(!pressed)clearFloat()};bt.onpointerdown=e=>{pressed={b,x:e.clientX,y:e.clientY,t:performance.now()};held=false;holdTimer=setTimeout(()=>{held=true;peek(b)},150)};bt.onpointerup=e=>{clearTimeout(holdTimer);const p=pressed;pressed=null;if(!p)return;if(Math.hypot(e.clientX-p.x,e.clientY-p.y)<12){if(held)setTimeout(clearFloat,80);else openBook(b)}};bt.onpointercancel=()=>{clearTimeout(holdTimer);pressed=null;clearFloat()};hits.appendChild(bt)})}
function setFace(b){face.style.backgroundImage=`url(${PHOTO})`;face.style.backgroundSize='auto 100%';face.style.backgroundPosition=b.id==='hamlet'?'62% center':'center'}
function openBook(b){clearFloat();setFace(b);title.textContent=b.title;author.textContent=b.author||'Edition details';detail.classList.add('on');detail.scrollTop=0;renderGrid(b.id)}
function close(){detail.classList.remove('on')}document.querySelector('#close').onclick=close;detail.addEventListener('click',e=>{if(e.target===detail)close()});
function renderGrid(skip){grid.innerHTML='';books.filter(b=>b.id!==skip).forEach(b=>{const bt=document.createElement('button');bt.className='more-book',th=document.createElement('div');th.className='thumb';th.style.backgroundImage=`url(${PHOTO})`;th.style.backgroundSize='cover';th.style.backgroundPosition='center';const s=document.createElement('span');s.textContent=b.title;const sm=document.createElement('small');sm.textContent=b.author;bt.append(th,s,sm);bt.onclick=()=>{openBook(b);detail.scrollTo({top:0,behavior:'smooth'})};grid.appendChild(bt)})}
photo.addEventListener('load',layout);addEventListener('resize',layout);layout();